modLoader="javafml"
loaderVersion="[37,)"
license="BSD 3-Clause"

[[mods]]
modId="watersource"
version="${file.jarVersion}"
displayName="Water Source"
credits="Java, Forge, Lemon Slice Studio"
authors="Gloridifice"
logoFile="watersource.png"
description='''
This is a mod added a Thirst and Drinking System and Coconut to Minecraft.
'''

[[dependencies.watersource]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.watersource]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

